package com.erik.canseco.appclima.presentattion.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val primaryLight = Color(0xFF805610)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDDB3)
val onPrimaryContainerLight = Color(0xFF291800)
val secondaryLight = Color(0xFF6F5B40)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFBDEBC)
val onSecondaryContainerLight = Color(0xFF271904)
val tertiaryLight = Color(0xFF51643F)
val onTertiaryLight = Color(0xFFFFFF)
val tertiaryContainerLight = Color(0xFFD4EABB)
val onTertiaryContainerLight = Color(0xFF102004)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF201B13)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF201B13)
val surfaceVariantLight = Color(0xFFF0E0CF)
val onSurfaceVariantLight = Color(0xFF4F4539)
val outlineLight = Color(0xFF817567)
val outlineVariantLight = Color(0xFFD3C4B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF362F27)
val inverseOnSurfaceLight = Color(0xFFFCEFE2)
val inversePrimaryLight = Color(0xFFF4BD6F)
val surfaceDimLight = Color(0xFFE4D8CC)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E5)
val surfaceContainerLight = Color(0xFFF9ECDF)
val surfaceContainerHighLight = Color(0xFFF3E6DA)
val surfaceContainerHighestLight = Color(0xFFEDE0D4)